# Generated by Django 3.0.5 on 2020-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('sku', models.TextField()),
                ('shipper', models.TextField()),
                ('ship_loc', models.TextField()),
                ('ship_intransit', models.TextField()),
                ('ship_backorder', models.TextField()),
                ('ship_perweek', models.TextField()),
                ('leadtime_core', models.TextField()),
                ('leadtime_growth', models.TextField()),
            ],
        ),
    ]
